name: Publish Python Package to PyPI

on:
  push:
    branches:
      - main  # Adjust this to your default branch
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel twine

      - name: Build the package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        if: matrix.python-version == '3.12'  # Publish only once, using Python 3.12
        env:
          TWINE_USERNAME: __token__  # Required for API token authentication
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*

      - name: Clean up build artifacts
        run: rm -rf dist build *.egg-info
